# Generated by Django 5.0.2 on 2024-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/images/profile_default.png",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
